name: BuildCommonProjects-OnLinux

on:
  push:
    branches: [ dev/* ]
  pull_request:
    branches: [ dev-* ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Microsoft .NET Core Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.403
    - name: NuGet Restore Dependencies
      run: dotnet restore ./src/Dep.Common.sln
    - name: Building
      run: dotnet build ./src/Dep.Common.sln --framework netcoreapp3.1 --configuration Release --no-restore
